<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="IsValidInterface" Id="{f18c148e-a18a-4c4d-b322-3d8ac753f575}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IsValidInterface : BOOL
VAR_INPUT
	ip : I_Base;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[IsValidInterface := (ip <> 0);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>